로그인 + 회원가입 기능 중간 구현
Ji-InPark/KioSchool pull request #1
Opened 2023-12-25 14:34 UTC by whddltjdwhd

2023-12-25 14:59 UTC, Ji-InPark requested changes
기본적으로 pr 올릴 때는 이 pr이 뭐하는 pr인지, 어떤 기능이 구현됐는지 아니면 수정됐는지에 대한 설명을 적어주셔야합니다.

화면이 추가됐다면 어떤 화면이 추가됐는지 사진도 첨부해주는게 좋구요.
다음부터는 제가 pr template 넣어둘테니 그거에 맞추어서 작성해주세요.

2023-12-25 14:59 UTC, Ji-InPark commented on src/page/User/Login.tsx
> +      const response = await userApi.post<any>(
왜 try catch를 사용하셨죠..?
axios에 then catch문을 사용하는게 훨씬 좋아보이네요

그리고 어차피 axios로 나오는 값이 promise이기 때문에 굳이 이 `handleSubmit` 메소드가 async해야할까 싶긴하네요.

2023-12-25 14:59 UTC, Ji-InPark commented on src/page/User/Login.tsx
> +      }
axios then catch를 사용하면 이 분기문도 필요없어집니다

2023-12-25 14:59 UTC, Ji-InPark commented on src/page/User/Login.tsx
> +    <Fragment>
Fragment를 안쓰고 <>만 써도 됩니다

2023-12-25 14:59 UTC, Ji-InPark commented on src/page/User/Register.tsx
> +    e.preventDefault(); // 버튼 클릭 시 페이지 새로고침 방지
여기서 새로고침이 되나요?? 

그리고 여기도 axios then catch 사용하는게 좋을 것 같습니다.

2023-12-25 14:59 UTC, Ji-InPark commented on src/page/User/Register.tsx
> +  const [isVeryfied, setIsVeryfied] = useState<boolean | null>(null);
boolean | null 밖에 안됐나요?
default로 false를 넣어주면 괜찮을 거 같은데요

2023-12-25 14:59 UTC, Ji-InPark commented on src/page/User/Register.tsx
> +    }
이런건 else를 쓰는것 보다 if문을 반대로 작성해서 위에서 return 하게끔 작성하는게 더 좋습니다.

2023-12-25 14:59 UTC, Ji-InPark commented on src/page/User/Register.tsx
> +        setIsSendCode(false);
실패했더라도 isSendCode가 false로 바뀌면 안되는거 아닌가요?

2023-12-26 09:46 UTC, whddltjdwhd commented on src/page/User/Register.tsx
> +    e.preventDefault(); // 버튼 클릭 시 페이지 새로고침 방지
`  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!userId || !password) {
      setErrorMessage('Both fields are required.');
      return;
    }
    userApi
      .post<any>(
        '/login',
        {
          id: userId,
          password: password,
        },
        {
          withCredentials: true,
        },
      )
      .then((response) => {
        console.log('Login successful:', response.data);

        setPassword('');
        setUserId('');

        // 로그인을 성공적으로 했을때
        navigate('/admin'); // Redirect to "/admin"
      })
      .catch((error) => {
        console.error('login error:', error);
        setErrorMessage('Invalid username or password');
      });
  };`

위에서 말씀하신 사항들 이렇게 수정했습니다.

2023-12-26 09:47 UTC, Ji-InPark commented on src/page/User/Register.tsx
> +    e.preventDefault(); // 버튼 클릭 시 페이지 새로고침 방지
아 수정하면 제가 어차피 다시 리뷰하니깐 이렇게 댓글로 어떻게 수정했는지는 안적어주셔도 괜찮아요~ 😄

2023-12-26 09:48 UTC, Ji-InPark commented on src/page/User/Register.tsx
> +    e.preventDefault(); // 버튼 클릭 시 페이지 새로고침 방지
그냥 반영했다면 resolve conversation만 해주시면 됩니다

2023-12-30 04:17 UTC, Ji-InPark approved these changes
리팩토링은 제가 진행하겠습니다 컨플릭 해결하고 머지해주세요~~
master로 리베이스 한 번 해주시면 될 것 같습니다.
수고하셨습니다~

2023-12-30 05:36 UTC, merged