EDIT - 회원가입 페이지 디자인 적용
Ji-InPark/KioSchool pull request #17
Opened 2024-01-23 14:47 UTC by whddltjdwhd

## 📚 개요

> 회원가입 페이지를 [디자인 문서](https://www.figma.com/file/sYBYaVOQ4RHsbghlf6YKBs/kioschool?type=design&node-id=151-512&mode=dev)를 참고하여 구현했습니다. 

## 🕐 리뷰 예상 시간

> 5m

## ❗❗ 중요한 변경점(Option)

![image](https://github.com/Ji-InPark/KioSchool/assets/81473218/5dd694ea-aeaf-4513-b751-873d94485320)

2024-01-23 15:08 UTC, Ji-InPark requested changes
전 개인적으로 애니메이션도 좋긴하지만 ux를 해치는 경우도 많다고 생각해서요.
또한 지금같은 경우에는 애니메이션을 위한 style이 한 파일에 너무 많이 있어서 파일을 읽기 힘들게 되기도 했구요.
애니메이션 유지를 원하신다면 style을 분리해서 가독성을 높여주시면 좋을 것 같습니다.

유지 하지 않는다면 code 인증 부분을 disable해두고 코드 전송 버튼을 눌렀을 때 enable해주는 방식으로도 구현할 수 있습니다!

또한 margin사용은 최대한 지양해주세요. 정말 유지보수가 어렵습니다...
login 페이지 참고하시면 충분히 대체 가능하실 겁니다

2024-01-23 15:08 UTC, Ji-InPark commented on src/page/User/Register.tsx
> +const RegisterMove = { marginTop: '25px' };
margin은 사용하지 말아주세요.

2024-01-23 15:08 UTC, Ji-InPark commented on src/page/User/Register.tsx
> +const RegisterMove = { marginTop: '25px' };
또한 이름들이 어색합니다. style 이름인데 동사로 시작해서 그런 것 같으니 다른 이름을 찾아보시는게 좋을 것 같아요

2024-01-23 15:09 UTC, Ji-InPark reviewed
로그인하기 버튼도 없네요 확인 후 추가해주세요~

2024-01-24 13:23 UTC, whddltjdwhd commented on src/component/common/input/AppInputWithLabel.tsx
> +  font-style: normal;
피그마에서 긁어온 값이었는데 디폴트 값이었군요 알겠습니다.

2024-01-24 13:25 UTC, Ji-InPark commented on src/component/common/input/AppInputWithLabel.tsx
> +  font-style: normal;
저도 잘 모릅니다! 찾아보고 반영해주세요!

2024-01-24 13:32 UTC, whddltjdwhd commented
디자인 대로 한다면 회원가입 버튼도 존재하지 않습니다. 그래서 로그인하기 버튼이 곧 회원가입 버튼이 자리할 위치구나 라고 생각하고 구현하였습니다. 이에 대해서는 디자이너분하고 상의해보겠습니다.

2024-01-24 14:40 UTC, whddltjdwhd commented
margin은 1개를 제외하고 모두 제거했습니다 
AppInputWithLabel에 message를 prop으로 넘겨서 출력하는 부분 작업하고 있습니다

2024-01-24 14:52 UTC, Ji-InPark reviewed
AppButton 기본값 변경으로 로그인 쪽 레이아웃이 틀어졌네요 이 부분 한 번 확인해주세요.

또한 비밀번호 확인 부분도 필요할 것 같습니다.

2024-01-24 15:00 UTC, whddltjdwhd commented
넵 로그인 컴포넌트도 고쳤습니다
비밀번호 확인하는 기능도 추가 구현하겠습니다

2024-01-24 16:06 UTC, Ji-InPark commented on src/page/User/Register.tsx
> +              messageLabel={isPasswordEntered ? (isSamePassword ? '비밀번호가 동일합니다!' : '비밀번호가 서로 다릅니다.') : undefined}
ternary는 chaining하지 말아주세요 이런 경우에는 메소드로 분리하시면 됩니다

2024-01-24 16:06 UTC, Ji-InPark commented on src/page/User/Register.tsx
> +  };
왜 ref를 사용하지 않고 이렇게 작성하셨나요...?

2024-01-24 16:07 UTC, whddltjdwhd commented on src/page/User/Register.tsx
> +  };
ref로 사용하게 되면 비밀번호 입력을 할때에 즉각적으로 확인할 수 없어서 useState로 바꿨습니다

2024-01-24 16:08 UTC, Ji-InPark commented on src/page/User/Register.tsx
> +  };
그런거라면 비밀번호 확인 부분만 usestate를 사용하면 될 것 같습니다.
둘 다 state일 필요는 없을 것 같아요

2024-01-24 16:21 UTC, whddltjdwhd commented on src/page/User/Register.tsx
> +  };
https://github.com/Ji-InPark/KioSchool/assets/81473218/672cb3bd-fc7f-4846-b810-dba5b680e07c

위처럼 확인 부분을 ref로 작성하게 되면 똑같은 비밀번호를 쳐도 확인이 되지 않습니다

2024-01-24 16:48 UTC, Ji-InPark approved these changes

2024-01-24 16:51 UTC, merged