사용자 계좌 추가 기능 구현
Ji-InPark/KioSchool pull request #26
Opened 2024-01-29 15:52 UTC by whddltjdwhd

## 📚 개요

 > 토스  QR코드를 읽고 QR코드에서 사용자의 계좌 정보를 추출하여 저장하는 기능 구현

## 🕐 리뷰 예상 시간

> 5m

## ❗❗ 중요한 변경점(Option)

> 토스 QR코드를 읽는 코드를 jsqr 라이브러리를 이용해 구현하였습니다.
> 사용자가 올린 QR코드를 인식하며 인식하지 못할 시 경고문구를 출력합니다.

2024-01-29 16:10 UTC, Ji-InPark requested changes
pr 작성하실 때 리뷰하는 사람이 따로 찾아보지 않아도 될만큼 최대한 자세하게 작성해주세요.
jsqr이 뭔지, page를 추가했으면 page가 어떤식으로 노출되는지, 어떤 기능이 구현됐는지 또는 어떤 부분을 신경써서 봐야하는지 등등

지금은 너무 간략하게 적혀있어서 제가 따로 찾아봐야하는 부분이 많았습니다.
pr description만으로 작성이 어렵다면 해당 코드에 직접 리뷰를 달아서 설명하셔도 됩니다.

리뷰 반영해주시고 rebase해서 컨플릭 처리도 해주세요~

2024-01-29 16:10 UTC, Ji-InPark commented on src/page/Admin/AdminAccount.tsx
> +    }
```suggestion
    imgUploadInput.current?.click();
```

2024-01-29 16:10 UTC, Ji-InPark commented on src/page/Admin/AdminAccount.tsx
> +    }
이것도 최대한 if문을 가독성 있게 바꿔보세요

2024-01-29 16:10 UTC, Ji-InPark commented on src/page/Admin/AdminAccount.tsx
> +        if (context) {
여기 부분도 가독성 좋게 바꿔주세요

2024-01-29 16:10 UTC, Ji-InPark commented on src/page/Admin/AdminAccount.tsx
> +          context.drawImage(image, 0, 0, image.width, image.height);
context를 onload 내부에서 생성하지 않고 외부에서 closure로 주입하신 이유가 따로 있나요?

2024-01-29 16:10 UTC, Ji-InPark commented on src/page/Admin/AdminAccount.tsx
> +    event.preventDefault();
button type이 submit이 아니라서 prevent하지 않아도 될 것 같은데 prevent하신 이유가 있으신가요?

2024-01-29 17:06 UTC, Ji-InPark commented on src/page/Admin/AdminAccount.tsx
> +      <img src={fileURL ? fileURL : 'https://cdn-icons-png.flaticon.com/512/1555/1555492.png'} />
로컬 파일이 아닌 프로젝트 파일은 접근 가능합니다.
해당 경로를 상대경로로 작성해주면 잘 찾습니다.

process.env.PUBLIC_URL 이걸 알아서 붙여준다고 생각하시면 돼여

2024-01-29 17:07 UTC, whddltjdwhd commented on src/page/Admin/AdminAccount.tsx
> +      <img src={fileURL ? fileURL : 'https://cdn-icons-png.flaticon.com/512/1555/1555492.png'} />
그럼 상대 경로 적어놓으면 배포시에 자동으로 처리가 되는건가요?

2024-01-29 17:17 UTC, Ji-InPark commented on src/page/Admin/AdminAccount.tsx
> +      <img src={fileURL ? fileURL : 'https://cdn-icons-png.flaticon.com/512/1555/1555492.png'} />
넵 애초에 프로젝트 파일에 있는 모든 파일들은 같이 배포됩니다.
그래서 이미지가 너무 무거운건 또 프로젝트 파일에서 빼라고도 하죠

2024-01-29 17:44 UTC, whddltjdwhd commented on src/page/Admin/AdminAccount.tsx
> +          context.drawImage(image, 0, 0, image.width, image.height);
이 부분은 외부 코드를 참고한거라 다른 이유는 없습니다. 함수 안으로 넣겠습니다

2024-01-29 17:49 UTC, whddltjdwhd commented on src/page/Admin/AdminAccount.tsx
> +          context.drawImage(image, 0, 0, image.width, image.height);
image.onload = () => {
      const context = canvas.getContext('2d');
      if (!context) return;

함수 안으로 넣게되면 이런 느낌이 되는데 안넣는거랑 비슷한 것 같아요. 

    const context = canvas.getContext('2d');
    image.onload = () => {
      if (!context) return;

2024-01-29 17:59 UTC, whddltjdwhd commented on src/page/Admin/AdminAccount.tsx
> +      image.src = fileURL;
아니요 순서는 상관이 없습니다

2024-01-30 00:45 UTC, Ji-InPark commented on src/page/Admin/AdminAccount.tsx
> +          context.drawImage(image, 0, 0, image.width, image.height);
함수를 pure하게 만들 수 있는데 굳이 closure를 사용하는 이유를 모르겠습니다.
현재 onload에 할당하는 함수가 람다라서 그렇지 해당 함수를 다른곳에서 정의하여 사용한다고 하면 현재 방식으로는 구현이 불가합니다.
웬만해서는 함수안으로 넣어주세요. 

pure한 함수가 뭔지 모르겠다면 한 번 찾아보시죠. 깔끔하고 유지보수가 되는 코드를 짜는데 중요한 것 중 하나입니다.

2024-01-30 00:52 UTC, Ji-InPark approved these changes

2024-01-30 00:52 UTC, Ji-InPark commented on src/page/Admin/AdminAccount.tsx
> +  const removeUsingRegex = (url: string): string => {
removeUsingRegex라고하면 regex를 이용해서 지운다는건데 뭘 지운다는건지 명확하지가 않습니다.
결국 코드 읽는 사람은 이 함수에 들어와서 해석까지 해야겠죠.

저는 removeAmountQuery 정도로 생각했습니다. 해당 함수에서 regex를 사용하는지 여부는 사용하는곳에서 별로 필요 없는 정보이니깐요.

2024-01-30 00:52 UTC, Ji-InPark commented on src/page/Admin/AdminAccount.tsx
> +    image.src = fileURL;
```suggestion
    const canvas = document.createElement('canvas');
    const context = canvas.getContext('2d');
    const image = new Image();
    image.src = fileURL;
```

선언과 사용부분은 최대한 붙여주시는게 좋습니다.

2024-01-30 00:52 UTC, Ji-InPark commented on src/page/Admin/AdminAccount.tsx
> +      <img src={fileURL || 'src\resourcedefault-image.png'} />
역슬래쉬로 제대로 동작하나요??

2024-01-30 00:52 UTC, Ji-InPark commented on src/resource/default-image.png
resource 폴더에 image같은 폴더를 만들어서 추가해주세요.

2024-01-30 00:52 UTC, Ji-InPark commented on src/page/Admin/AdminAccount.tsx
> +      addAccount(url);
```suggestion
      registerAccount(url);
```
아직 반영이 안됐네요

2024-01-30 01:17 UTC, Ji-InPark requested changes
approve 잘못 눌렀습니다~

2024-01-30 12:13 UTC, whddltjdwhd commented on src/page/Admin/AdminAccount.tsx
> +      <img src={fileURL || 'src\resourcedefault-image.png'} />
src/resource/default-image.png 이렇게 작성했는데도 지금은 보이질 않네요 그냥 이대로 갈까요?

2024-01-30 12:16 UTC, whddltjdwhd commented on src/page/Admin/AdminAccount.tsx
> +      <img src={fileURL || 'src\resourcedefault-image.png'} />
'/resource/image/default-image.png' 이렇게 해도 여전히 똑같아요

2024-01-30 12:17 UTC, Ji-InPark commented on src/page/Admin/AdminAccount.tsx
> +      <img src={fileURL || 'src\resourcedefault-image.png'} />
작업하신거 올려주시죠 한 번 확인해볼게요

2024-01-30 12:42 UTC, Ji-InPark commented on src/page/Admin/AdminAccount.tsx
> +      <img src={fileURL || 'src\resourcedefault-image.png'} />
간단하게는 https://stackoverflow.com/questions/37644265/correct-path-for-img-on-react-js
이것처럼 import해서 사용하는게 제일 간단하겠네요. 다만 ts라서 error를 뱉을겁니다.
그럼 import 구문에다가 `// @ts-ignore` 하나만 붙여주는 식으로 구현하시죠.
ts를 아래 한 줄 한정해서 무시하겠다는 구문입니다.

2024-01-30 12:42 UTC, Ji-InPark commented on src/page/Admin/AdminAccount.tsx
> +      <img src={fileURL || 'src\resourcedefault-image.png'} />
편하게 사용하게 만드려면 꽤 많은 작업이 필요해서 그건 제가 하겠습니다

2024-01-30 12:49 UTC, Ji-InPark commented on src/page/Admin/AdminAccount.tsx
> +import defaultImage from '../../resource/image/defaultImage.png';
지금보니깐 이미지 이름 너무 general하네요
더 명시적으로 수정해주세요.

2024-01-30 13:06 UTC, whddltjdwhd commented on src/page/Admin/AdminAccount.tsx
> +import defaultImage from '../../resource/image/defaultImage.png';
고민 많이 했습니다..

2024-01-30 13:07 UTC, Ji-InPark commented on src/page/Admin/AdminAccount.tsx
> +import defaultImage from '../../resource/image/defaultImage.png';
음... ㅎㅎ 지금도 너무 general한데....
상품도 이미지 업로드 할 텐데 그 때도 공통으로 사용하는건가요?? 그러면 목적에 맞다고 볼 수 있습니다

2024-01-30 13:08 UTC, merged